<a href="https://colab.research.google.com/github/plkimtuyen05-boop/ktltsp.ueh25/blob/Kim-Tuy%E1%BB%81n/buoi_03_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
v = list(range(1, 6))
v
2 * v
import numpy as np
v = np.arange(1, 6)
v
2 * v

array([ 2,  4,  6,  8, 10])

In [2]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90

In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c

array([ 4, 10, 18])

In [6]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a.shape)

(3, 5)

In [10]:
import numpy as np
a = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)
int64

In [13]:
import pandas as pd
from IPython.display import display
df = pd.DataFrame({"a": [4, 5, 6],
                   "b": [7, 8, 9],
                  "c": [10, 11, 12]},
                 index = [1, 2, 3])
display(df)
display(df['a'])

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

1    4
2    5
3    6
Name: a, dtype: int64

In [14]:
type(df)

pandas.core.frame.DataFrame

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported

In [16]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [17]:
dates = pd.date_range('20181001',periods=6)
dates

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [19]:
df = pd.DataFrame(np.random.randn(6,4),
index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2018-10-01 -1.186463  0.202091 -0.299682 -0.750573
2018-10-02  0.090976  1.084387  0.664842 -0.643485
2018-10-03  0.505345 -0.123000  1.270796  0.320471
2018-10-04 -1.406551  1.273531 -1.686660  0.832302
2018-10-05  0.392158 -0.023882 -0.882264  0.056673
2018-10-06  1.216663 -0.698934  0.810613 -0.613659

In [20]:
df = pd.DataFrame(np.random.randn(3,5),
index=['student1','student2','student3']
, columns=list('ABCDE'))
df

                 A         B         C         D         E
student1  0.193128  0.954695  0.855699 -0.007491  0.810227
student2  0.591173  1.144165 -2.130422 -0.146988 -1.154819
student3  0.860828  0.310359 -0.164270  0.900957 -0.089610

In [21]:
df2 = pd.DataFrame(
    {
        'A' : 1.,
        'B' : pd.Timestamp('20181001'),
        'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
        'D' : np.array([3] * 4,dtype='int32'),
        'E' : pd.Categorical(["test","train","test","train"]),
        'F' : 'foo' })
df2

     A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [3]:
df3 = pd.DataFrame(
    [{'A':1.0, 'B': pd.Timestamp('20181001'), 'C':2.5, 'D': 3, 'E': 'test', 'F': 'fod'}])
df3

     A          B    C  D     E    F
0  1.0 2018-10-01  2.5  3  test  fod